// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_zxAefhhYAitpFmZWFSlf-bYQ025gEqw',
    appId: '1:420980287728:web:2c93d427dfe875149dfa35',
    messagingSenderId: '420980287728',
    projectId: 'en-joint',
    authDomain: 'en-joint.firebaseapp.com',
    storageBucket: 'en-joint.appspot.com',
    measurementId: 'G-HTT1CHN3WM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWHa1ltghagASwcFzbPpZgBKsUnVhqhbo',
    appId: '1:420980287728:android:c760971a62d7b1519dfa35',
    messagingSenderId: '420980287728',
    projectId: 'en-joint',
    storageBucket: 'en-joint.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYtlSFcnMjYJIzXd6Xd3TRNvLzbv1Q0S0',
    appId: '1:420980287728:ios:f5351a09dde3218b9dfa35',
    messagingSenderId: '420980287728',
    projectId: 'en-joint',
    storageBucket: 'en-joint.appspot.com',
    iosClientId: '420980287728-qqfd5ntpash6bk39jgaac0sf1dqp1gpt.apps.googleusercontent.com',
    iosBundleId: 'com.example.enJoint',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYtlSFcnMjYJIzXd6Xd3TRNvLzbv1Q0S0',
    appId: '1:420980287728:ios:f5351a09dde3218b9dfa35',
    messagingSenderId: '420980287728',
    projectId: 'en-joint',
    storageBucket: 'en-joint.appspot.com',
    iosClientId: '420980287728-qqfd5ntpash6bk39jgaac0sf1dqp1gpt.apps.googleusercontent.com',
    iosBundleId: 'com.example.enJoint',
  );
}
